services:

  hospital:
    image: hospital:0.0.1-SNAPSHOT
    ports:
      - "8074:8074"
    depends_on:
      - zookeeper
      - kafka
    #      - postgres-hospital
    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-hospital:5432/hospital
  #      - SPRING_DATASOURCE_USERNAME=postgres
  #      - SPRING_DATASOURCE_PASSWORD=postgres
  #      - SPRING_JPA_HIBERNATE_DDL-AUTO=update

  hospital_2:
    image: hospital_2:0.0.1-SNAPSHOT
    ports:
      - "8075:8075"
    depends_on:
      - zookeeper
      - kafka
#      - postgres-hospital
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-hospital_2:5431/hospital_2
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL-AUTO=update

#  postgres-hospital:
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=hospital

  #  postgres-hospital_2:
  #    image: postgres
  #    ports:
  #      - "5431:5431"
  #    environment:
  #      - POSTGRES_PASSWORD=postgres
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_DB=hospital_2


  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:0.47.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1