create table employee (
    id int8 generated by default as identity,
    first_name varchar(255) not null,
    second_name varchar(255) not null,
    role varchar(255) not null,
    qualification varchar(255) not null,
    username varchar(255) unique not null,
    password varchar(255) not null,
    active boolean not null,
    primary key (id)
);

create table event (
    id int8 generated by default as identity,
    prescription_id int8,
    date_time timestamp,
    event_status varchar(255) not null,
    comment varchar(255),
    patient_id int8,
    primary key (id)
);

create table patient (
    id int8 generated by default as identity,
    first_name varchar(255) not null,
    second_name varchar(255) not null,
    insurance varchar(255) not null,
    diagnosis varchar(255) not null,
    status varchar(255) not null,
    doctor_id int8,
    primary key (id)
);

create table prescription (
    id int8 generated by default as identity,
    patient_id int8,
    end_treatment date not null,
    start_treatment date not null,
    treatment_type varchar(255) not null,
    treatment_description varchar(255) not null,
    dose varchar(255) not null,
    doctor_id int8,
    primary key (id)
);

create table treatment_time (
    prescription_id int8 not null,
    treatment_time varchar(255)
);

alter table if exists event add constraint event_patient_fk foreign key (patient_id) references patient;
alter table if exists event add constraint event_prescription_fk foreign key (prescription_id) references prescription;
alter table if exists patient add constraint patient_employee_fk foreign key (doctor_id) references employee;
alter table if exists prescription add constraint prescription_employee_fk foreign key (doctor_id) references employee;
alter table if exists prescription add constraint prescription_patient_fk foreign key (patient_id) references patient;
alter table if exists treatment_time add constraint treatment_time_prescription_fk foreign key (prescription_id) references prescription;