create table appointment (
    id int8 generated by default as identity,
    doctor_id int8,
    date_time timestamp not null,
    is_vacant boolean not null,
    primary key (id)
);

alter table if exists appointment add constraint appointment_employee_fk foreign key (doctor_id) references employee;

--insert into appointment(doctor_id, date_time, is_vacant)
--    values(2, '22-Jun-2022 10:00', true);